name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          # Compile the source code and generate artifacts (no compilation needed for HTML)
          # Generate artifacts (e.g., minify CSS and JS files)
          npm install
          npm run build

      - name: Test
        run: |
          # Run unit tests and code quality checks (no tests for HTML)
          # Run code quality checks (e.g., code coverage, code analysis)
          # No tests or code quality checks needed for HTML

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          password: ${{ secrets.STAGING_PASSWORD }}
          script: |
            # Deploy the application to a staging environment
            cd /path/to/staging/environment
            rm -rf *
            cp -r ./* .