name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          # Compile the source code and generate artifacts
          mkdir build
          cd build
          cmake ..
          make

      - name: Test
        run: |
          # Run unit tests and code quality checks
          make test
          ./build/test

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          password: ${{ secrets.STAGING_PASSWORD }}
          script: |
            # Deploy the application to the staging environment
            cd /path/to/staging/environment
            cp -r ./build/* .
            ./start-app.sh